# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
 platform :ios, '8.0'
target 'test_thread' do
pod 'AFNetworking','~>2.5.0'
pod 'STAlertView','~>1.0.0'
end

target 'test_threadTests' do
pod 'AFNetworking','~>2.5.0'
pod 'STAlertView','~>1.0.0'
end

target 'test_threadUITests' do

end

